Kili/Models/General/Abonnement.cs
using Kili.Models;
using Kili.Models.Dons;
using Kili.Models.Vente;
using Kili.Models.GestionAdhesion;
using System.Collections.Generic;

namespace Kili.Models.General
{
    public class Abonnement
    {
        public int Id { get; set; }

        public int? ServiceAdhesionId { get; set; }
        public virtual ServiceAdhesion serviceAdhesion { get; set; }
        public int? ServiceDonId { get; set; }

        public virtual ServiceDon serviceDon { get; set; }
        public int? ServiceBoutiqueId { get; set; }
        public virtual ServiceBoutique serviceBoutique { get; set; }
        public virtual Association Association { get; set; }    

      


        public Abonnement()
        {
            serviceAdhesion = new ServiceAdhesion() { EstActif = false};
            serviceDon = new ServiceDon() { EstActif = false };
            serviceBoutique = new ServiceBoutique() { EstActif = false};
        }


        


    }
}

Kili/Models/General/PanierService.cs
using System.Collections.Generic;
using Kili.Models.Services;

namespace Kili.Models.General
{
    public class PanierService
    {
        public int Id { get; set; }
        public virtual List<Item> Items { get; set; }
    }
}

Kili/Models/Services/PanierServices.cs
using System.Collections.Generic;
using System.Linq;
using Kili.Models.Vente;
using Microsoft.EntityFrameworkCore;

namespace Kili.Models.Services
{
    public class PanierServices
    {
        private BddContext _bddContext;
        public PanierServices()
        {
            _bddContext = new BddContext();
        }

        public int CreerPanier()
        {
            Panier panier = new Panier() { Articles = new List<Article>() };
            _bddContext.Paniers.Add(panier);
            _bddContext.SaveChanges();
            return panier.PanierID;
        }

        public Panier ObtenirPanier(int panierId)
        {
            return _bddContext.Paniers.Include(p=> p.Articles).ThenInclude(xx=> xx.Produit).Where(c=> c.PanierID == panierId).FirstOrDefault();
        }

        public void AjouterArticle(int PanierId, Article article)
        {
            Panier panier = _bddContext.Paniers.Find(PanierId);
            panier.Articles.Add(article);

            _bddContext.SaveChanges();
        }

        public void MettreAjourQuantite(int ArticleID)
        {
            var article = _bddContext.Articles.Find(ArticleID);
            if(article != null)
            {
                article.Quantite += 1;
                _bddContext.SaveChanges();
            }
        }

        public void SupprimerArticle(int PanierID, int ArticleID)
        {
            Panier panier = ObtenirPanier(PanierID);
            Article article = panier.Articles.Where(yy => yy.ArticleId == ArticleID).FirstOrDefault();
            panier.Articles.Remove(article);
            _bddContext.SaveChanges();
        }
    }
}

Kili/Models/Services/Vente_Services/PanierServices.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Kili.Models.Vente;
using Microsoft.AspNetCore.Mvc;
using Kili.Models;
using Kili.Models.General;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Web.Http.Common;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Http.Connections;
using Microsoft.AspNetCore.Http.Features;
using Owin;
using Microsoft.AspNetCore.Identity;
using System.Web.Http;
using System.Threading;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Core;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Internal;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Net.Http.Headers;
using System;
using System.IO;
using System.Linq.Expressions;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;


namespace Kili.Models.Services.Vente_Services
{
    public class PanierServices : IDisposable
    {
        public string ShoppingID { get; set; }
        private BddContext _bddContext = new BddContext();

        public const string CleSessionPanier = "PanierID";

        public void AjouterDansPanier(int id)
        {
            //Récupérer le produit de la base de données
            ShoppingID = ObtenirArticleID();

            var articlePanier = _bddContext.Paniers.SingleOrDefault(
                a => a.PanierID == ShoppingID
                && a.ProduitID == id);
            if (articlePanier == null)
            {
                // Créer un nouvel article de panier si aucun article de panier n'existe.
                articlePanier = new Panier
                {
                    ArticleID = Guid.NewGuid().ToString(),
                    ProduitID = id,
                    PanierID = ShoppingID,
                    Produit = _bddContext.Produits.SingleOrDefault(
                        p => p.ProduitID == id),
                    Quantite = 1,
                    DateCreation = DateTime.Now
                };
                _bddContext.Paniers.Add(articlePanier);
            }
            else
            {
                // Si l'article existe dans le panier, en rajouter un à la quantité.
                articlePanier.Quantite++;
            }
            _bddContext.SaveChanges();
        }
        public void Dispose()
        {
            if (_bddContext != null)
            {
                _bddContext.Dispose();
                _bddContext = null;
            }
        }
        public string ObtenirArticleID()
        {
            if(HttpContext.Session
        }
    }
}

Kili/Models/Services/Vente_Services/Panier_Services.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Kili.Models.Vente;

namespace Kili.Models.Services.Vente_Services
{
    public class Panier_Services
    {
        private BddContext _bddContext;
        public Panier_Services()
        {
            _bddContext = new BddContext();
        }

        //Fonction permettant d'obtenir la liste de tous les paniers
        public List<Panier> ObtenirAllPaniers()
        {
            return _bddContext.Paniers.ToList();
        }

        //Fonction permettant d'obtenir un panier à partir de son Id
        public Panier ObtenirPanier(int id)
        {
            return _bddContext.Paniers.Find(id);
        }

        //Fonction permettant d'obtenir un panier à partir de son Id en format string
        public Panier ObtenirPanier(string idstr)
        {
            int id;
            if (int.TryParse(idstr, out id))
            {
                return this.ObtenirPanier(id);
            }
            return null;
        }

        //Fonction permettant de créer un panier
        public string CreerPanier(int quantitePanier, DateTime dateCreationPanier, int produitIDpanier)
        {
            Panier panier = new Panier()
            {
                Quantite = quantitePanier,
                DateCreation = dateCreationPanier,
                ProduitID = produitIDpanier
            };
            _bddContext.Paniers.Add(panier);
            _bddContext.SaveChanges();
            return panier.ArticleID;
            
        }
    }
}

Kili/Controllers/AbonnementController.cs
using Kili.Helpers;
using Microsoft.AspNetCore.Mvc;
using Kili.Models.Services;
using Kili.Models.General;
using System.Collections.Generic;
using Kili.ViewModels;
using Kili.Models;

namespace Kili.Controllers
{
    public class AbonnementController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public PanierService ObtenirPanierService()
        {
            var cartId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cartId");
            PanierService cart;
            if (cartId != 0)
            {
                cart = new PanierService_Services().GetCart(cartId);
            }
            else
            {
                cart = new PanierService() { Items = new List<Item>() };
            }
            return cart;
        }

        public IActionResult ConfirmerPaiementService()
        {
            var cartId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cartId");
            PanierService cart;
            cart = new PanierService_Services().GetCart(cartId);


            foreach (Item item in cart.Items)
            {
                new Abonnement_Services().AjouterService(new UserAccount_Services().ObtenirUserAccountConnecte(User.Identity.Name).Association.Id, item.Service);
            }

            SupprimerPanier();
            return View("ConfirmationPaiement");
        }

        public IActionResult AjouterService(int id)
        {
            var cartId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cartId");
            PanierService_Services PanierService_Services = new PanierService_Services();

            if (cartId == 0)
            {
                // Le panier n'existe pas donc on le crée en ajoutant l'item dedans
                cartId = PanierService_Services.CreateCart();
                PanierService_Services.AddItem(cartId, new Item { ServiceId = id, Quantity = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cartId", cartId);
            }
            else
            {
                // Le panier existe deja, on ajoute alors l'item
                PanierService panier = PanierService_Services.GetCart(cartId);
                int res = ServiceExisteDansPanier(panier, id);
                if (res != -1)
                {
                //    PanierService_Services.UpdateItemQuantity(res);
                }
                else
                {
                    PanierService_Services.AddItem(cartId, new Item { ServiceId = id, Quantity = 1 });
                }
            }
            //return View("../Association/GererServices", new ServicesViewModel());
            //return RedirectToAction("PanierServices");
            return RedirectToAction("GererServices", "Association");
        }

        public IActionResult PanierServices()
        {
            return View(ObtenirPanierService());
        }

        public IActionResult SupprimerServiceDansPanier(int id)
        {
            var panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cartId");
            new PanierService_Services().RemoveItem(panierId, id);
            
            return RedirectToAction("PanierServices");

        }


        public IActionResult SupprimerPanier()
        {
            var panierId = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "cartId");
            new PanierService_Services().DeleteCart(panierId);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cartId", 0);
            return RedirectToAction("GererServices", "Association");
        }


        private int ServiceExisteDansPanier(PanierService panier, int ServiceId)
        {
            foreach (var item in panier.Items)
            {
                if (item.Service.Id == ServiceId)
                {
                    return item.Service.Id;
                }
            }
            return -1;
        }

    }
}

Kili/Views/Abonnement/ConfirmationPaiement.cshtml
@model Kili.ViewModels.PaiementViewModel
@{
    Layout = "_Layout";
    ViewBag.Title = "Paiement";
}


        <body>

        <section id="home" classedata-stellar-background-ratio="0.5">


          <div class="row">
               <div class="col-75">
                 <div class="container" style="margin:200px;">

                   
                       <div class="col-50">
                         <h3>Votre commande a été prise en compteVos Services sont à présent actifs</h3>
                         <h3>Vos Services sont à présent actifs</h3>

                         <button type="button" class="button">@Html.ActionLink("Accéder à votre page association", "VoirProfilAssociation", "Association")</button>



                       </div>

                     </div>
        
          </div>
         </div>


     </section>


    </body>

Kili/Views/Abonnement/PanierServices.cshtml
@model Kili.Models.General.PanierService;
@{
    Layout = "_Layout";
    ViewBag.Title = "Panier";
}


<body>
    
    <!-- intro boutique -->
    <section id="section-kili" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>

        <div class="container">
            <div class="Liste-panier">
                <div class="col-xl-12 col-lg-12 col-md-10 col-sm-12 col-md-12">
                    <section class="card">
                        <H3 style="text-align:center;"> Panier</H3>
                        <!------------------------------------------- Ligne du premier article-->
                        <ul class="list-group-item align-items-center">
                            <li class="list-group-item align-items-center drag-handle">
                                <span class="drag-indicator"></span>
                                <div class="col-sm-10">
                                    <div class="col-md-2 col-md-10">IdService</div>
                                    <div class="col-md-2 col-md-10">Produit</div>
                                    <div class="col-md-2 col-md-10">Durée</div>
                                    <div class="col-md-2 col-md-10">Quantité</div>
                                    <div class="col-md-2 col-md-10">Prix</div>
                                    <div class="col-md-2 col-md-10">Sous-Total</div>
                                </div>
                                <button style="color:transparent;background-color:transparent;border:none;">ce bouton est pour la mise en page il ne sert a rien </button>

                            </li>
                        </ul>
						
                           @{
                                double total = 0;
                            }

                         @foreach (var item in Model.Items)
                         {
                        <!------------------------------------------- Ligne du deuxieme article-->
                        <ul class="list-group-item align-items-center drag-handle">
                            <li class="list-group-item align-items-center drag-handle ">
                                <span class="drag-indicator"></span>
                                <div class="col-sm-10">
                                    <div class="col-md-2 col-md-10">@item.Service.Id</div>
                                    <div class="col-md-2 col-md-10">@item.Service.TypeService</div>
                                    <div class="col-md-2 col-md-10">@item.Service.duree_mois</div>
                                    <div class="col-md-2 col-md-10">@item.Quantity</div>
                                    <div class="col-md-2 col-md-10">@item.Service.prix €</div>
                                    <div class="col-md-2 col-md-10">@(item.Service.prix * item.Quantity) €</div>

                                                                                @{
                                                total = total + (item.Service.prix * item.Quantity);
                                            }
                                </div>

                                <button type="button" class="btn btn-default">@Html.ActionLink("Supprimer", "SupprimerServiceDansPanier", "Abonnement", new { id = @item.Id })</button>

                                

                            </li>
                        </ul>
                         }

                      <!-------------------------------------------- ligne Total-------------->

                                                               

                      <ul class="list-group-item align-items-center">
                            <li class="list-group-item align-items-center drag-handle">
                                <span class="drag-indicator"></span>
                                <div class="col-sm-10">
                                    <div class="col-md-2 col-md-10">Total</div>
                                    <div class="col-md-2 col-md-10"></div>
                                    <div class="col-md-2 col-md-10"></div>
                                    <div class="col-md-2 col-md-10"></div>
                                    <div class="col-md-2 col-md-10"></div>
                                    <div class="col-md-2 col-md-10">@total €</div>
                                </div>
                                <button style="color:transparent;background-color:transparent;border:none;">ce bouton est pour la mise en page il ne sert a rien </button>
                            </li>
                        </ul>
                       

                        <!-------------------------------------------- ligne validation-------------->

                        <ul class="list-group-item align-items-center drag-handle">
                            <li class="list-group-item align-items-center drag-handle ">
                                <span class="drag-indicator"></span>
                    
                        
                        <button button type="button" class="btn btn-default">@Html.ActionLink("Annuler", "SupprimerPanier", "Abonnement")</button>
                        <button button type="button" class="button" id="btn-val">@Html.ActionLink("Continuer mes achats", "GererServices", "Association")</button>
                        <button button type="button" class="button" id="btn-val">@Html.ActionLink("Payer", "CreerPaiementServices", "Paiement", new {montant = @total})</button>

                            </li>
                        </ul>
                    </section>

                </div>
            </div>
        </div>
    </section>




</body>