Kili/Models/Dons/Collecte.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Kili.Models.Dons
{
    public class Collecte
    {
        public int Id { get; set; }
        [MaxLength(300)]
        [Required]
        public string Nom { get; set; }
        public int MontantCollecte { get; set; }      
        public string  Descriptif { get; set; }

        public bool Actif { get; set; }

        public string ImagePath { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }

        public DateTime Date { get; set; }
        public int? ServiceDonId { get; set; }
        public virtual ServiceDon ServiceDon { get; set; }
        public ICollection<Don> Dons { get; set; }

    }
}

Kili/Controllers/CollecteController.cs
using Kili.Models;
using Kili.Models.Dons;
using Kili.Models.General;
using Kili.Models.Services;
using Kili.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using static Kili.ViewModels.PaiementViewModel;

namespace Kili.Controllers
{
    public class CollecteController : Controller
    {

        private IWebHostEnvironment _webEnv;

        public CollecteController(IWebHostEnvironment environment)
        {
            _webEnv = environment;
        }

        // Création d'une collecte (à mettre depuis la page association)
        public IActionResult CreerCollecte()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreerCollecte(Collecte collecte)
        {
            //if (!ModelState.IsValid) { 
            UserAccount_Services userAccount_Services = new UserAccount_Services();

            DonServices donServices = new DonServices();
            {

                if (collecte.Image != null)
                {
                    if (collecte.Image.Length != 0)
                    {
                        string uploads = Path.Combine(_webEnv.WebRootPath, "images");
                        string filePath = Path.Combine(uploads, collecte.Image.FileName);
                        using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            collecte.Image.CopyTo(fileStream);
                        }

                        donServices.CreerCollecte(collecte.Nom, collecte.MontantCollecte, collecte.Descriptif, userAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).Association.Abonnement.ServiceDonId, "/images/" + collecte.Image.FileName);
                                            }
                }
                else
                {
                    donServices.CreerCollecte(collecte.Nom, collecte.MontantCollecte, collecte.Descriptif, userAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).Association.Abonnement.ServiceDonId,null);
                }

               return Redirect("/collecte/AfficherCollectesDonsCompteConnecte"); 
            }
            // } return View();
        }

        // Affiche une collecte à partir de son id
        public IActionResult AfficherCollecte(int id)
        {
            Collecte collecte = new DonServices().ObtenirCollecte(id);
            if (collecte != null)
            {            
                DonViewModel viewModel = new DonViewModel() { Don = new Don(), Collecte =collecte, IdCollecte = collecte.Id};

                return View(viewModel);

            }
            return View("Error");
        }

        [HttpPost]
        public IActionResult AfficherCollecte(DonViewModel viewModel)
        {
            UserAccount_Services UserAccount_Services = new UserAccount_Services();

            if (HttpContext.User.Identity.IsAuthenticated)
            {
                DonServices donservices = new DonServices();

                //Fonction plus utilisé car nous ne requèrons finalement pas un champ adresse pour etre donateur. 
                /*
                //Regarde si l'utilisateur n'a pas d'adresse enregistrée et alors le redirige vers la création d'une adresse
                if (UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).AdresseId == null)
                {
                    return Redirect("/adresse/creeradresse");
                }
                */

                //Regarde si l'utilisateur n'est pas enregistré comme donateur et alors crée un donateur en y associant l'Id de l'adresse
                if (UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).DonateurId == null)
                {

                    UserAccount ua = UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name);

                    // ATTENTION FONCTION A TESTER : il s'agit d'une rustine temporaire du fait qu'une adresse n'est plus nécessaire.
                    int idtemp = donservices.CreerDonateur();

                    UserAccount_Services.ModifierUserAccount(ua.Id, ua.Prenom, ua.Nom, ua.Mail, ua.Telephone, ua.Role, ua.AssociationId, idtemp, ua.AdresseId, ua.ImagePath);

                }

                //Fonction plus utilisée car on ne demande plus nécessairement l'adresse.
                /*
               //Si l'utilisateur est déjà donateur, alors on modifie celui-ci en y associant l'adresse
               else
               {
                   donservices.ModifierDonateur((int)UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).DonateurId, UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).AdresseId);

               }*/

                int id = donservices.CreerDon(viewModel.Don.Montant, viewModel.Don.Recurrence, UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).DonateurId, viewModel.IdCollecte);

                return RedirectToAction("CreerPaiement", "Paiement", new { actionID = id, montant = viewModel.Don.Montant, typeaction = TypeAction.Don });
            }
            else
            {
                return RedirectToAction("Authentification", "Login");
            }
        }


        // Affiche la liste des collectes de la BDD
        public IActionResult AfficherCollectes()
        {
            DonServices donServices = new DonServices();
            {
                List<Collecte> listcollecte = donServices.ObtenirCollectesActives();

                return View(listcollecte);
            }
        }

        // Affiche la liste des collecte d'une association à partir de son Id
        public IActionResult AfficherCollectesAssociation(int id)
        {

            UserAccount_Services UserAccount_Services = new UserAccount_Services();
            List<Collecte> listcollecteAsso = new List<Collecte>();
            {

                foreach (Collecte collecte in UserAccount_Services.ObtenirUserAccount(id).Association.Abonnement.serviceDon.Collectes)
                {
                    listcollecteAsso.Add(collecte);
                }

                return View(listcollecteAsso);
            }
        }

        // Liste de collecte visible par le compte utilisateur 

        public IActionResult AfficherCollectesCompteConnecte()
        {
            
            UserAccount_Services UserAccount_Services = new UserAccount_Services();
            List<Collecte> listcollecteAsso = new List<Collecte>();
            {

                foreach (Collecte collecte in UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).Association.Abonnement.serviceDon.Collectes)
                {
                    listcollecteAsso.Add(collecte);
                }

                return View(listcollecteAsso);
            }
        }

        // Liste de collectes et de dons visibles par le compte utilisateur
        public IActionResult AfficherCollectesDonsCompteConnecte()
        {

            UserAccount_Services UserAccount_Services = new UserAccount_Services();

            CollecteDonViewModel collecteDonViewModel = new CollecteDonViewModel() { listecollecte = new List<Collecte>(), listedon = new List<Don>(), montantglobalcollectes=0};

            collecteDonViewModel.association = UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).Association;

            foreach (Collecte collecte in UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).Association.Abonnement.serviceDon.Collectes)
                {
                
                if (collecte.Actif == true) { 
                   collecteDonViewModel.listecollecte.Add(collecte);
                }

                collecteDonViewModel.montantglobalcollectes += collecte.MontantCollecte;


                if (collecte.Dons != null)
                {

                foreach (Don don in collecte.Dons) {

                    collecteDonViewModel.listedon.Add(don);                    
                    }         
                }

                }
            

            return View(collecteDonViewModel);            
        }

        // Modifie une collecte à partir de son Id
        public IActionResult ModifierCollecte(int id)
        {
            if (id != 0)
            {
                DonServices donServices = new DonServices();
                {
                    Collecte collecte = donServices.ObtenirCollecte(id);

                    if (collecte == null)
                    {
                        return View("Error");
                    }
                    return View(collecte);
                }

            }
            return View("Error");
        }

        [HttpPost]
        public IActionResult ModifierCollecte(Collecte collecte)
        {

            if (collecte.Id != 0)
            {
                DonServices donServices = new DonServices();


                if (collecte.Image != null)
                {
                    if (collecte.Image.Length != 0)
                    {
                        string uploads = Path.Combine(_webEnv.WebRootPath, "images");
                        string filePath = Path.Combine(uploads, collecte.Image.FileName);
                        using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            collecte.Image.CopyTo(fileStream);
                        }
                        donServices.ModifierCollecte(collecte.Id, collecte.Nom, collecte.MontantCollecte, collecte.Descriptif, collecte.Date, "/images/" + collecte.Image.FileName);
                    }
                }
                else
                {
                    donServices.ModifierCollecte(collecte.Id, collecte.Nom, collecte.MontantCollecte, collecte.Descriptif, collecte.Date, collecte.ImagePath);
                }
       

Kili/Controllers/DonController.cs
using Kili.Models;
using Kili.Models.Dons;
using Kili.Models.Services;
using Kili.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using Kili.Models.General;
using static Kili.ViewModels.PaiementViewModel;

namespace Kili.Controllers
{
    //[Authorize]
    public class DonController : Controller 
    {

        // Fonction permettant de creer un don à partir dun id de collecte.

        public IActionResult CreerDon(int idCollecte)
        {
            UserAccount_Services UserAccount_Services = new UserAccount_Services();

            UserAccountViewModel viewModel = new UserAccountViewModel { Authentifie = HttpContext.User.Identity.IsAuthenticated };
            DonViewModel donviewModel = new DonViewModel { IdCollecte = idCollecte, Authentifie = HttpContext.User.Identity.IsAuthenticated };

            // valide si l'utilisateur est authentifié
            if (viewModel.Authentifie)
            {
                //Regarde si l'utilisateur n'a pas d'adresse enregistrée et alors le redirige vers la création d'une adresse
                if (UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).AdresseId == null)
                {
                    return Redirect("/adresse/creeradresse");
                }

                DonServices donservices = new DonServices();

                //Regarde si l'utilisateur n'est pas enregistré comme donateur et alors crée un donateur en y associant l'Id de l'adresse
                if (UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).DonateurId == null) {

                    UserAccount ua = UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name);

                    int id = donservices.CreerDonateur(ua.AdresseId);

                    UserAccount_Services.ModifierUserAccount(ua.Id, ua.Prenom, ua.Nom, ua.Mail, ua.Telephone, ua.Role, ua.AssociationId, id, ua.AdresseId, ua.ImagePath );

                }

                //Si l'utilisateur est déjà donateur, alors on modifie celui-ci en y associant l'adresse
                else
                {
                    donservices.ModifierDonateur((int)UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).DonateurId, UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).AdresseId);
                
                }

                return View(donviewModel);
            }
            return Redirect("/login/authentification");
        }


        [HttpPost]
        public IActionResult CreerDon(DonViewModel viewModel)
        {
            //if (!ModelState.IsValid) { 

            UserAccount_Services UserAccount_Services = new UserAccount_Services();
            DonServices donServices = new DonServices();
            {
                int id = donServices.CreerDon(viewModel.Don.Montant, viewModel.Don.Recurrence, UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name).DonateurId, viewModel.IdCollecte);               
                
                return RedirectToAction("creerpaiement", "paiement", new { actionID = id, montant = viewModel.Don.Montant, typeaction = TypeAction.Don });
            }
            // } return View();


        }

        // Affiche un don à partir d'un id
        public IActionResult AfficherDon(int id)
        {
            if (id != 0)
            {
                DonServices donServices = new DonServices();
                {
                    Don don = donServices.ObtenirDon(id);
                    if (don == null)
                    {
                        return View("Error");
                    }
                    return View(new DonViewModel() { Don = don });
                }

            }
            return View("Error");
        }


        // Affiche l'ensemble des dons de la bdd. 
        public IActionResult AfficherDons()
        {
            DonServices donServices = new DonServices();
                {
                    List<Don> listdon = donServices.ObtenirDons();
                    
                return View(listdon);
                }
        }

        // Modifie un don à partir de son Id. 
        public IActionResult ModifierDon(int id)
        {
            if (id != 0)
            {
                    DonServices donServices = new DonServices();
                    {
                    Don don = donServices.ObtenirDons().Where(r => r.Id == id).FirstOrDefault();

                    if (don == null)
                    {
                        return View("Error");
                    }
                    return View(new DonViewModel() { Don = don });
                }

            }
            return View("Error");
        }

        [HttpPost]
        public IActionResult ModifierDon(DonViewModel viewModel)
        {

            if (viewModel.Don.Id != 0)
            {
                    DonServices donServices = new DonServices();
                    {
                    donServices.ModifierDon(viewModel.Don.Id, viewModel.Don.Montant, viewModel.Don.Recurrence);

                    return RedirectToAction("ModifierDon", new { @id = viewModel.Don.Id });
                }
            }
            else
            {
                return View("Error");
            }
        }

           
        // Supprimer un don à partir de son Id
            public IActionResult SupprimerDon(int id)
        {
            if (id != 0)
            {
                    DonServices donServices = new DonServices();
                    {
                    Don don = donServices.ObtenirDons().Where(r => r.Id == id).FirstOrDefault();
                    if (don == null)
                    {
                        return View("Error");
                    }
                    donServices.SupprimerDon(id);
                    return Redirect("/home/index");
                }

            }
            return View("Error");
        }





}
}

Kili/Views/Collecte/AfficherCollecte.cshtml
@model Kili.ViewModels.DonViewModel
@using Kili.Models
@using Kili.Models.Dons

@{
    Layout = "_Layout";
    ViewBag.Title = "Index";
}


     <link rel="stylesheet" href="~/css/Vignettestyle.css">
     <link rel="stylesheet" href="~/css/ModalCot.css">
@*
<body>*@

     

<section data-stellar-background-ratio="0.5">
          <div class="overlay"></div>
          <p style="color:transparent">----------------------------------------------------</p>
          <p style="color:transparent">----------------------------------------------------</p>
          <div class="container">
               <div class="row">
                    <div class="col-md-12">
                         <div class="col-md-6 col-md-6">
                                   <h1>@Model.Collecte.Nom</h1>
                                   <br>
                                   <h4>@Model.Collecte.Descriptif</h4><br>

                                   <p><b>Faire un don à cette collecte</b></p>
                                   
                                    @using (Html.BeginForm())
                                    {
                                    <fieldset class="register-form" id="register-form">
                                         <div class="search_box_2">
                                    @Html.TextBoxFor(m => m.Don.Montant,  new { @id="montantDon", @placeholder="" , @required="required", @class="input_search" })
                                    

                                    @Html.DropDownListFor(m => Model.Don.Recurrence, new SelectList(Enum.GetValues(typeof(Kili.Models.Dons.TypeRecurrence))), "Sélectionner une récurrence" ,new{@class="input_search"})
                                     </div>
                                    @Html.HiddenFor(m => Model.IdCollecte)
                                    
                                    <div class="form-submit">                            
                                    <br><input type="submit" value="Donner" class="submit button" name="submit" id="submit" />
                                    </div>
                                    
                                    </fieldset>

                                    }
                     </div>
                                       
                     <div class="col-md-6 col-md-6">
                              <img src="@Model.Collecte.ImagePath" alt="" height="500" width="750" style="border-radius: 10%;">
                        </div>
                 
                 </div>
        </div>
    </div>
</section>





<!-- SCRIPTS -->
@*<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery.stellar.min.js"></script>
<script src="~/js/owl.carousel.min.js"></script>
<script src="~/js/smoothscroll.js"></script>
<script src="~/js/custom.js"></script>
<script>src="~/js/ModalCOT.js"</script>

</body>*@

Kili/Views/Collecte/AfficherCollectes.cshtml
@model IEnumerable<Kili.Models.Dons.Collecte>

    @{
    Layout = "_Layout";
    ViewBag.Title = "Visualisez les collectes";
}

 <div><b>Liste des collectes</b><br /></div>  
    <table class="table table-bordered table-responsive table-hover">  
    <tr>  
        <th>Nom</th>      
        <th>Date</th>  
        <th>Recurrence</th>   
    </tr>  
    @foreach (var v in Model)  
    {  
        <tr>
            <td>@v.Nom</td>   
            <td>@v.Date.ToLongDateString()</td>  
            <td>@v.Descriptif</td>
            <td>@Html.ActionLink("Faire un don", "CreerDon", "Don", new { idCollecte = @v.Id })</td>
        </tr>  
    }  
     <!-- id = 1 à changer pour l'Id de la collecte sélecionnée dans le tableau-->
</table> 

Kili/Views/Collecte/AfficherCollectesCompteConnecte.cshtml
@model IEnumerable<Kili.Models.Dons.Collecte>

    @{
    Layout = "_Layout";
    ViewBag.Title = "Visualisez les collectes";
}

 <div><b>Liste des collectes</b><br /></div>  
    <table class="table table-bordered table-responsive table-hover">  
    <tr>
        <th>Nom</th>
        <th>Montant</th>  
        <th>Date</th>  
        <th>Recurrence</th>   
    </tr>  
    @foreach (var v in Model)  
    {  
        <tr>
            <td>@v.Nom</td>  
            <td>@v.MontantCollecte</td>  
            <td>@v.Date</td>  
            <td>@v.Descriptif</td>
            <td>@Html.ActionLink("Supprimer", "SupprimerCollecte", "Collecte", new { id = @v.Id })</td>
            <td>@Html.ActionLink("Modifier", "ModifierCollecte", "Collecte", new { id = @v.Id })</td>
        </tr>  
    }  
     <!-- id = 1 à changer pour l'Id de la collecte sélecionnée dans le tableau-->
</table> 

Kili/Views/Collecte/CreerCollecte.cshtml
@model Kili.Models.Dons.Collecte

@{
    Layout = "_Layout";
    ViewBag.Title = "Créez votre collecte";
}

 @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Créez votre collecte </legend><br />
            @Html.LabelFor(m => Model.Nom)
            @Html.TextBoxFor(m => Model.Nom)
            <br /><br />
            @Html.LabelFor(m => Model.Descriptif)
            @Html.TextAreaFor(m => Model.Descriptif)
            <br /><br />
            <!--<label for="datecol">Date de fin</label>-->
            <!--<input type="datetime" id="datecol" name="datecol" value="_____Model.Date"/>-->
            <br /><br />
            <input type="submit" value="Créer" />
        </fieldset>
    }

Kili/Views/Collecte/ModifierCollecte.cshtml
@model Kili.Models.Dons.Collecte

@{
    Layout = "_Layout";
    ViewBag.Title = "Modifiez votre collecte";
}

 @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Modifiez votre collecte </legend><br />
            @Html.LabelFor(m => Model.Nom)
            @Html.TextBoxFor(m => Model.Nom)
            <br /><br />
            @Html.LabelFor(m => Model.Descriptif)
            @Html.TextAreaFor(m => Model.Descriptif)
            <br /><br />
            <label for="datecol">Date</label>
            <input type="date" id="datecol" name="datecol" value="@Model.Date"/>
            <br /><br />
            <input type="submit" value="Modifier" />
            @Html.HiddenFor(m => Model.Id)
        </fieldset>
        @Html.ActionLink("Supprimer votre collecte", "SupprimerCollecte", "Collecte", new { id = Model.Id })
    }