Kili/Controllers/LoginController.cs
using Kili.Models;
using Kili.Models.General;
using Kili.Models.Services;
using Kili.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace Kili.Controllers
{
    public class LoginController : Controller
    {
        private UserAccount_Services UserAccount_Services;

        public LoginController()
        {
            UserAccount_Services = new UserAccount_Services();
        }


        public IActionResult Authentification(UserAccountViewModel viewModel)
        {
                
               viewModel.Authentifie = HttpContext.User.Identity.IsAuthenticated ;
                if (viewModel.Authentifie)
                {
                    viewModel.UserAccount = UserAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name);
                    return View(viewModel);
                }
                return View(viewModel);
        }

        [HttpPost]
        public IActionResult Authentification(UserAccountViewModel viewModel, string returnUrl)
        {

            if (ModelState.IsValid)
             {

                UserAccount utilisateur = UserAccount_Services.Authentifier(viewModel.UserAccount.Mail, viewModel.UserAccount.Password);
                if (utilisateur != null)
                {
                    var userClaims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, utilisateur.Id.ToString()),
                        new Claim(ClaimTypes.Role, utilisateur.Role.ToString()),
                    };

                    var ClaimIdentity = new ClaimsIdentity(userClaims, "User Identity");

                    var userPrincipal = new ClaimsPrincipal(new[] { ClaimIdentity });

                    HttpContext.SignInAsync(userPrincipal, new AuthenticationProperties() { IsPersistent = false });

                   /* if (returnUrl != null)
                        return Redirect(returnUrl);*/
                   if (!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                        return Redirect(returnUrl);

                    return Redirect("/");
                }
                ModelState.AddModelError("UserAccount.UserName", "UserName et/ou mot de passe incorrect(s)");
                return RedirectToAction("Authentification", ModelState);
            }
            ModelState.AddModelError("UserAccount.UserName", "UserName et/ou mot de passe incorrect(s)");
            return RedirectToAction("Authentification");
            //viewModel.Authentifie = HttpContext.User.Identity.IsAuthenticated;

            //return View("../Home/Index", new IndexViewModel() { Authentifie = HttpContext.User.Identity.IsAuthenticated , Associations = new Association_Services().Obtenir3DernièresAssociations() });

        }

        public ActionResult Deconnexion()
        {
            HttpContext.SignOutAsync();
            return Redirect("/");
        }

        public void DeconnexionDemarrage()
        {
            try { HttpContext.SignOutAsync(); }
            catch (Exception e)
            {
            }           
        }
    }
}

Kili/Controllers/VenteController.cs
using Microsoft.AspNetCore.Mvc;
using Kili.Models.Vente;
using Kili.Models.Services;
using System.Linq;
using System.Collections.Generic;
using Kili.Helpers;
using Kili.Models;
using System.Threading.Tasks;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Kili.Models.General;
using Kili.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
namespace Kili.Controllers
{
    public class VenteController : Controller
    {
        private CatalogueServices _CatalogueServices;
        private ProduitServices _ProduitServices;
        private PanierServices _PanierServices;
        private CommandeServices _CommandeServices;
        private LivraisonServices _LivraisonServices;
        private CoordonneesAcheteur _CoordonneesAcheteur;
        private BddContext _bddContext;
        private IWebHostEnvironment _WebEnv
;


        public VenteController(IWebHostEnvironment webEv)
        {
            _CatalogueServices = new CatalogueServices();
            _ProduitServices = new ProduitServices();
            _PanierServices = new PanierServices();
            _CommandeServices = new CommandeServices();
            _LivraisonServices = new LivraisonServices();
            _CoordonneesAcheteur = new CoordonneesAcheteur();
            _bddContext = new BddContext();
            _WebEnv = webEv;
        }

        //FONCTIONS POUR LES CATALOGUES

        //GET Afficher la liste des catalogues
        public IActionResult IndexCatalogue()
        {
            CatalogueServices catservice = new CatalogueServices();
            List<Catalogue> catalogues = catservice.ObtenirAllCatalogues();
            return View(catalogues);
        }

        //GET Formulaire création de catalogue
        public IActionResult CreerCatalogue()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreerCatalogue(Catalogue catalogue)
        {
            if (!ModelState.IsValid)
                return View();
            CatalogueServices catalogueService = new CatalogueServices();
            {
                catalogueService.CreerCatalogue(catalogue.CatalogueName, catalogue.Description);
                return RedirectToAction("IndexCatalogue");
            }
        }

        //GET Vue catalogue à modifier

        public IActionResult ModifierCatalogue(int? id)
        {
            // int testint = (int) id;
            if (id.HasValue)
            {
                CatalogueServices catservice = new CatalogueServices();
                Catalogue cata = catservice.ObtenirAllCatalogues().FirstOrDefault(c => c.CatalogueID == id.Value);
                if (cata == null)
                    return NotFound();
                return View(cata);
            }
            else
                return NotFound();
        }

        [HttpPost]

        public IActionResult ModifierCatalogue(Catalogue catalogue)
        {
            if (!ModelState.IsValid)
                return View(catalogue);
            CatalogueServices catservice = new CatalogueServices();
            catservice.ModifierCatalogue(catalogue.CatalogueID, catalogue.CatalogueName, catalogue.Description);
            return RedirectToAction("IndexCatalogue");

        }

        public IActionResult SupprimerCatalogue(int id)
        {

            CatalogueServices catservice = new CatalogueServices();
            catservice.SupprimerCatalogue(id);
            return RedirectToAction("IndexCatalogue");
        }



        //FONCTIONS POUR LES PRODUITS

        //Fonctions GET
        public IActionResult IndexProduit()
        {
            ProduitServices prodservice = new ProduitServices();
            List<Produit> produits = prodservice.ObtenirAllProduits();
            return View(produits);
        }
        public IActionResult CreerProduit()
        {

            CatalogueServices catservice = new CatalogueServices();
            List<Catalogue> catalogues = catservice.ObtenirAllCatalogues();
            ViewBag.Catalogue = new SelectList(catalogues, "CatalogueID", "CatalogueName"); ;
            return View();
        }

        [HttpPost]
        public IActionResult CreerProduit(Produit produit)
        {
            if (!ModelState.IsValid)
                return View();

            if (produit.Image.Length > 0)
            {
                string uploads = Path.Combine(_WebEnv.WebRootPath, "images");
                uploads = Path.Combine(uploads, "Produit");
                string filePath = Path.Combine(uploads, produit.Image.FileName);

                using (var stream = System.IO.File.Create(filePath))
                {
                    produit.Image.CopyTo(stream);

                }

                produit.ImagePath = "/images/Produit/" + produit.Image.FileName;


                ProduitServices produit_Services = new ProduitServices();

                produit_Services.CreerProduit(produit.DateCreation, produit.Designation, produit.Format, produit.Description, produit.ImagePath, produit.PrixUnitaire, produit.Devise, produit.CatalogueID);
                return RedirectToAction("IndexProduit");

            }
            return View(produit);
        }





        //GET Vue produit à modifier
        public IActionResult ModifierProduit(int? id)
        {
            if (id != 0)
            {
                ProduitServices prodservice = new ProduitServices();
                {
                    Produit produit = prodservice.ObtenirAllProduits().Where(p => p.ProduitID == id).FirstOrDefault();
                    if (produit == null)
                    {
                        return NotFound();
                    }
                    return View(produit);
                }

            }
            return NotFound();
        }

        //POST Vue produit à modifier
        [HttpPost]
        public IActionResult ModifierProduit(Produit produit)
        {
            if (!ModelState.IsValid)
                return View(produit);
            ProduitServices produitServices = new ProduitServices();
            produitServices.ModifierProduit(produit.ProduitID, produit.DateCreation, produit.Designation, produit.Format, produit.ImagePath, produit.Description, produit.PrixUnitaire, produit.Devise);
            return RedirectToAction("IndexProduit");
        }

        //Supprimer Produit

        public IActionResult SupprimerProduit(int id)
        {
            ProduitServices prodservice = new ProduitServices();
            prodservice.SupprimerProduit(id);
            return RedirectToAction("IndexProduit");
        }

        //Fonctions GET POUR PANIER

        //Afficher la liste des produits disponibles pour achat

        public IActionResult IndexBoutique()
        {
            var bdd = new BddContext();
            var produits = bdd.Produits.ToList();
            ViewBag.Produits = produits;
            return View();
        }
        //Afficher panier
        public IActionResult Panier()
        {
            var panierID = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierID");
            Panier panier;
            if (panierID != 0)
            {
                panier = new PanierServices().ObtenirPanier(panierID);
            }
            else
            {
                panier = new Panier() { Articles = new List<Article>() };
            }
            return View(panier);

        }

        public IActionResult Acheter(int id)
        {
            var panierID = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierID");
            PanierServices panierServices = new PanierServices();
            if (panierID == 0)
            {
                //Si le panier n'existe pas, créer le panier avant d'ajouter un article de produit à l'intérieur
                panierID = panierServices.CreerPanier();
                panierServices.AjouterArticle(panierID, new Article { ProduitID = id, Quantite = 1 });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "panierID", panierID);
            }
            else
            {
                //Si le panier existe, rajouter un article à l'intérieur
                Panier panier = panierServices.ObtenirPanier(panierID);
                int res = ProduitExistantDansPanier(panier, id);
                if (res != -1)
                {
                    panierServices.MettreAjourQuantite(res);
                }
                else
                {
                    panierServices.AjouterArticle(panierID, new Article { ProduitID = id, Quantite = 1 });
                }
            }
            return RedirectToAction("Panier");
        }

        public IActionResult SupprimerArticle(int id)
        {
            var panierID = SessionHelper.GetObjectFromJson<int>(HttpContext.Session, "panierID");
            new PanierServices().SupprimerArticle(panierID, id);
            return RedirectToAction("Panier");
        }

        //Renvoyer ArticleID si le produit est dans l'article, sinon renvoyer -1

        private int ProduitExistantDansPanier(Panier panier, int produitID)
        {
            foreach (var article in panier.Articles)
            {
                if (article.ProduitID == produitID)
                {
                    return article.ArticleId;
                }
            }
            return -1;
        }

        //Fonctions pour la livraison

        //GET Afficher le choix de livraisons possibles

        public IActionResult Livraison()
        {
            UserAccount_Services userAccount_Services = new UserAccount_Services();
            UserAccount ua = userAccount_Services.ObtenirUserAccount(HttpContext.User.Identity.Name);
            LivraisonServices livservice = new LivraisonServices();
            CommandeServices commandeServices = new CommandeServices();
            commandeServices.CreerCommande(this.GetSessionCart());

            LivraisonViewModel livraisonViewModel = new LivraisonViewModel();

Kili/Views/Shared/CreerUserAccount.cshtml
@model Kili.ViewModels.UserAccountViewModel

@{
    Layout = "_Layout";
    ViewBag.Title = "Créer votre compte";
}

 @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Créer votre compte utilisateur </legend><br />
            @Html.LabelFor(m => Model.UserAccount.UserName)
            @Html.TextBoxFor(m => Model.UserAccount.UserName)
            @Html.ValidationMessageFor(m => Model.UserAccount.UserName)
            <br /><br />
            @Html.LabelFor(m => Model.UserAccount.Password)
            @Html.TextBoxFor(m => Model.UserAccount.Password)
            @Html.ValidationMessageFor(m => Model.UserAccount.Password))
            <br /><br />
            @Html.LabelFor(m => Model.UserAccount.Mail)
            @Html.TextBoxFor(m => Model.UserAccount.Mail)
            @Html.ValidationMessageFor(m => Model.UserAccount.Mail)
            <br /><br />
            <input type="submit" value="Continuer" />
        </fieldset>
    }

    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.js"></script>

Kili/Views/Shared/_Layout.cshtml
@{
    @using Kili.Models.General;
    @using Kili.Models.Services;
}

<!DOCTYPE html>
<html lang="fr">

<head>

     <title>Kili</title>
  
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="team" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

     <!-- Index boostrap -->
     <link rel="stylesheet" href="~/css/bootstrap.min.css">
     <link rel="stylesheet" href="~/css/owl.carousel.css">
     <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
     <link rel="stylesheet" href="~/css/font-awesome.min.css">
     
     <!-- Index CSS -->
     <link rel="stylesheet" href="~/css/boutique-asso-style.css">
     <link rel="stylesheet" href="~/css/pop-up-style.css">
     <link rel="stylesheet" href="~/css/index-style.css">

     <link rel="stylesheet" href="~/css/Assostyle.css">
    <link rel="stylesheet" href="~/css/Team.css">
     <link href="bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/js/jquery-ui/jquery-ui-1.10.1.custom.min.css" rel="stylesheet">
    <link href="~/css/bootstrap-reset.css" rel="stylesheet">
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/js/jvector-map/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <link href="~/css/clndr.css" rel="stylesheet">
    <!--clock css-->
    <link href="~/js/css3clock/css/style.css" rel="stylesheet">
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="js/morris-chart/morris.css">
    <!-- Custom styles for this template -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/style-responsive.css" rel="stylesheet" />
   
    <link rel="icon" type="image/png" href="images/favicon.ico" />


      <!-- boutique CSS Bootstrap -->

</head>

<body>

     <!-- MENU -->
     <section class="navbar custom-navbar navbar-fixed-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="@Url.ActionLink("Index", "Home", new { viewModel = @Model})" class="smoothScroll">
                        <img src="/images/logo.png" class="navbar-brand" alt="">
                    </a>
               </div>

               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

                         <li><a href=@Url.ActionLink("VoirAssociations", "Home") class="smoothScroll">Les associations</a></li>
                         <li><a href="#pricing" class="smoothScroll">Nos services</a></li>
                        

                    </ul>
                
                
                @if (User.Identity.IsAuthenticated == false)
                {
                    <ul class="nav navbar-nav navbar-right">

                        <button type="button" class="btn btn-primary btn-lg show-modal" data-toggle="modal"
                              data-target="#myModal">Connexion</button>

                    </ul>

                    <!-- pop up connexion -->
                    @using (Html.BeginForm("Authentification", "Login"))
                    {
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content clearfix">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                             aria-hidden="true">×</span></button>
                                    <div class="modal-body">
                                        <h3 class="title">Connexion</h3>
                                        <p class="description">Saisir l'email et le mot de passe ! </p>
                                        <div class="form-group">
                                            <span class="input-icon"><i class="fa fa-user"></i></span>
                                            <input type="email" name="UserAccount.Mail" class="form-control" placeholder="Email" required="required">
                                        </div>
                                        <div class="form-group">
                                            <span class="input-icon"><i class="fa fa-shield"></i></span>
                                            <input type="password" name="UserAccount.Password" class="form-control" placeholder="Mot de passe" required="required">
                                        </div>
                                        <div class="form-group checkbox">
                                            <input type="checkbox">
                                            <label>Sauvegarder</label>
                                        </div>

                                        <a href="" class="forgot-pass">Mot de passe oublié ?</a>
                                        <input type="submit" value="Se connecter" class="btn" name="submit" id="submit" />

                                        <div class="form-group-connex">
                                     <a  href="Create.html" >@Html.ActionLink("Créer un compte", "CreerUtilisateur", "UserAccount")</a> <br><br>
                                        <a  href="Create.html"><strong>@Html.ActionLink("Inscrire votre association", "AjouterCompteAssociation", "Association")</strong></a>
                                         </div>

                                    </div>
                                </div>
                            </div>


                        </div>
                    }
                }
                @if (User.Identity.IsAuthenticated == true)
                {
                    <div class="top-nav clearfix">

                        <ul class="nav pull-right top-menu">

                            <!-- user login dropdown start-->
                    <li class="dropdown">
                                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                    @{
                                        UserAccount compteconnecte = new UserAccount_Services().ObtenirUserAccountConnecte(User.Identity.Name);
                                    }
                                      <img alt="" src=@compteconnecte.ImagePath height="20" width="20" style="border-radius:10%">
                                      <span class="username">@compteconnecte.Prenom</span>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu extended logout">
                                    <li>@Html.ActionLink("Mon Profil", "ModifierUserAccount", "UserAccount", new {id = @compteconnecte.Id})</li>
                                    @{
                                        if (User.IsInRole ("Association"))
                                    {
                                        <li>@Html.ActionLink("Mon Association", "VoirProfilAssociation", "Association")</li>
                                    }
                                    <li>@Html.ActionLink("Se deconnecter", "Deconnexion", "Login")</li>
                                    }
                        </ul>
                    </li>
                    <!-- user login dropdown end -->
                
                </ul>
                <!--search & user info end-->
            </div>
                }
            </div>
     </section>
     <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.0.min.js"></script><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
-->

     <!-- intro boutique -->
     <div>@RenderBody()</div>
         
         
     <!-- FOOTER -->
     <footer id="footer" data-stellar-background-ratio="0.5">
          <div class="container">
               <div class="row">

                    <div class="copyright-text col-md-12 col-sm-12">

                         <div class="col-md-12 col-md-3">
                              <ul>
                                   
                                   <img src="/images/logo.png" class="logo-footer" alt="">
                                   <span class="glyphicon glyphicon-envelope"> contact@kili.fr</span></br>
                                   <span class="glyphicon glyphicon-envelope"> +33 1 89 21 45 96</span>
                                   <ul class="social-icon">
                                        <li><a href="#" class="fa fa-twitter"></a></li>
                                        <li><a href="#" class="fa fa-instagram"></a></li>
                                   </ul>
                              </ul>
                         </div>
                         <div class="col-md-12 col-md-3">
                              <ul>
                                   <h3>Particuliers</h3>
                                   <a>Boutiques</a></br>
                                   <a>Collectes</a></br>
                                   <a>Adhésion</a></br>
                              </ul>
                         </div>
                         <div class="col-md-3 col-md-3">
                              <ul>
                                   <h3>Associations </h3>
                                   <a>Abonnement</a></br>
                                   <a>Offres</a></br>
                                   <a>Aide</a></br>
                              </ul>
                         </div>
                         <div class="col-md-3 col-md-3">
                              <ul>
                                   <h3>L'équipe Kili </h3>

                                    <div class="container-footer">
                                        <img src="/images/actu-footer.jpg" alt="Notebook" style="width:100%;">
                                        <div class="content-footer">
                                          <a href=@Url.Action("Team","Home")><h1>Rencontrons-nous !</h1></a>
                                        </div>
                                      </div>
                              </ul>
                         </div>
                        
                         <div class="col-md-12 col-sm-12">
                              <img src="/images/image-footer.png" class="image-footer" alt="">
                              <p>Copyright &copy; 2022 Company Kili - Project </p>

                         </div>

               
                         
                    </div>

               </div>
          </div>
     </footer>


     <!-- SCRIPTS -->
     <script src="~/js/jquery.js"></script>
     <script src="~/js/bootstrap.min.js"></script>
     <script src="~/js/jquery.stellar.min.js"></script>
     <script src="~/js/owl.carousel.min.js"></script>
     <script src="~/js/smoothscroll.js"></script>
     <script src="~/js/custom.js"></script>

     <script src="js/jquery.js"></script>
    <script src="js/jquery-ui/jquery-ui-1.10.1.custom.min.js"></script>
    <script src="bs3/js/bootstrap.min.js"></script>
    <script src="js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="js/jquery.scrollTo.min.js"></script>
    <script src="js/jQuery-slimScroll-1.3.0/jquery.slimscroll.js"></script>
    <script src="js/jquery.nicescroll.js"></script>
    <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
    <script src="js/skycons/skycons.js"></script>
    <script src="js/jquery.scrollTo/jquery.scrollTo.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="js/calendar/clndr.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>
    <script src="js/calendar/moment-2.2.1.js"></script>
    <script src="js/evnt.calendar.init.js"></script>
    <script src="js/jvector-map/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="js/jvector-map/jquery-jvectormap-us-lcc-en.js"></script>
    <script src="js/gauge/gauge.js"></script>
    <!--clock init-->
    <script src="js/css3clock/js/css3clock.js"></script>
    <!--Easy Pie Chart-->
    <script src="js/easypiechart/jquery.easypiechart.js"></script>
    <!--Sparkline Chart-->
    <script src="js/sparkline/jquery.sparkline.js"></script>
    <!--Morris Chart-->
    <script src="js/morris-chart/morris.js"></script>
    <script src="js/morris-chart/raphael-min.js"></script>
    <!--jQuery Flot Chart-->
    <script src="js/flot-chart/jquery.flot.js"></script>
    <script src="js/flot-chart/jquery.flot.tooltip.min.js"></script>
    <script src="js/flot-chart/jquery.flot.resize.js"></script>
    <script src="js/flot-chart/jquery.flot.pie.js"></script>
    <script src="js/flot-chart/jquery.flot.animator.min.js"></script>
    <script src="js/flot-chart/jquery.flot.growraf.js"></script>

    <script src="~/js/LienIdpourPopup.js"></script>

    <script src="js/dashboard.js"></script>
    <script src="js/jquery.customSelect.min.js"></script>
    <!--common script init for all pages-->
    <script src="js/scripts.js"></script>
    <!--script for this page-->



</body>

</html>

Kili/Views/Shared/_ProductCarouselPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <!--/.carousel-indicator -->
    <ol class="carousel-indicators">
        <li data-target="#header-carousel" data-slide-to="0" class="active"><span class="small-circle"></span></li>
        <li data-target="#header-carousel" data-slide-to="1"><span class="small-circle"></span></li>
        <li data-target="#header-carousel" data-slide-to="2"><span class="small-circle"></span></li>
    </ol><!-- /ol-->
    <!--/.carousel-indicator -->
    <!--/.carousel-inner -->
    <div class="carousel-inner" role="listbox">
        @{
            int i = 0;
        }
        @foreach (var prod in ViewBag.Produits)
        {
            <!-- .item -->
            <div class="item @(i == 0 ? "active" : "")">

                <div class="single-slide-item slide1">

                    <div class="container">
                        <div class="welcome-hero-content">

                            <div class="row">

                                <div class="col-sm-7">
                                    <div class="single-welcome-hero">
                                        <div class="welcome-hero-txt">
                                            <h4>Produits d'exception</h4>

                                            <h2>@prod.Designation </h2>
                                            <p>
                                                @prod.Description
                                            </p>
                                            <div class="packages-price">
                                                <p>
                                                    € @prod.PrixUnitaire
            
                                                </p>
                                            </div>
                                            @Html.ActionLink("Acheter", "Acheter", "Vente", new { id = @prod.ProduitID, @class="btn btn-success", @label="Add to cart" })
                                            @*<button class="btn-cart welcome-add-cart" onclick="window.location.href='#'">
                                                <span class="lnr lnr-plus-circle"></span>
                                                add <span>to</span> cart
                                                </button>*@
                                            @*<button class="btn-cart welcome-add-cart welcome-more-info" onclick="window.location.href='#'">
                                                more info
                                            </button>*@
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-5">
                                    <div class="single-welcome-hero">
                                        <div class="welcome-hero-img">
                                            <img src="@prod.ImagePath" alt="slider image">
                                        </div><!--/.welcome-hero-txt-->
                                </div><!--/.single-welcome-hero-->
                            </div><!--/.col-->
                        </div><!--/.row-->
                    </div>
                    </div>
                </div>

            </div>
            i++;
        }
    </div>
</div>